### ISSUE TITLE
Testnet send-many contract not deployed since last reset

### ISSUE THREAD

**Issue by zone117x** [blockstack/send-many-stx-cli#4]
The contract hard coded in the code and mentioned in the readme is no longer deployed:
https://explorer.stacks.co/txid/STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C.send-many?chain=testnet

Do we still have access to the private key for `STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C`? If so, we should re-deploy. If not, we need to re-deploy with a new account and update the code and readme.

cc @hstove @diwakergupta @CharlieC3

**Comment by CharlieC3** [comment]
I don't have anything regarding this address on my end.

**Comment by zone117x** [comment]
Maybe we wait a couple days to see if @hstove originally deployed it and still has the keypair (and has time to help out). If not, we re-deploy and update the code.
